### ISSUE TITLE
[Enhancement] Functional inventory to VR

### ISSUE THREAD

**Issue by TinyDerp** [DaXcess/CWVR#18] opened 2024-05-13 14:50 UTC
I had an idea on how to make the inventory slots switchable in VR.
First we can get rid of the crouching button and make it so if you crouch in real life you crouch in game (and while we are at, jumping in real life makes you jump in game). Secund by adding a inventory menu similar to HL2 VR mod (not Half Life Alex, but might be I haven't played) and binding it to the pevieous crouch button. I know it's hard to make interfaces and that you probablly have your hands full with the LCVR mod, so I think you can just make it scrolled trough the inventory and everyone would be happy two.
And again thanks for this amazing mod and don't worry about taking your time with this one, stress is a b*tch.

**Comment by DaXcess** [comment] 2024-05-13 20:12
Duplicate of #11 and #14 

> For item swapping, press and hold the "Interact" button, and use "Zoom In" and "Zoom Out" to cycle through your inventory. Item swapping has been made this way as to not interfere with the camera zooming.

https://thunderstore.io/c/content-warning/p/DaXcess/CWVR/wiki/1966-controls/

**Closed by DaXcess** 2024-05-13 20:12 UTC
